### PR TITLE
Add CLI support

### LINKED ISSUE #200: Support running from CLI
### Expected Behavior

Allow to run and configure the plugin from the command line. Example: 

```
$  mvn nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.1.0:schemaspy -DdatabaseType=pgsql -Dhost=localhost -Dport=5432 -Ddatabase=test -Duser=testuser -Dpassword=testuser -DoutputDirectory=/tmp

```

### Actual Behavior

> [ERROR] Failed to execute goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.1.0:schemaspy (default-cli) on project myproject: The parameters 'database' for goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.1.0:schemaspy are missing or invalid 

### Required Changes

If I'm not mistaken all `@Parameter` annotations in [SchemaSpyReport.java](https://github.com/GeoDienstenCentrum/schemaspy-maven-plugin/blob/master/src/main/java/com/wakaleo/schemaspy/SchemaSpyReport.java#L75) need a `property` attribute.

### PR DESCRIPTION
**Pull request by marcelstoer**
Fixes #200

### CODE REVIEW

**Comment by mprins** [comment]
I'm not opposed to this addition, so I will merge, but if you want to run from the commandline you might be better off using https://github.com/schemaspy/schemaspy instead as that has improved on the actual schema spy code as well. Unfortunately in a  way that makes re-use impossible bacsue of wrapping everything-and-the-kitchensink up in a large runnable jar. 

See also https://github.com/schemaspy/schemaspy/issues/277

**Comment by marcelstoer** [comment]
Yes, I'm aware of this. The benefit of running SchemaSpy through Maven is that you get dependency management for free. Otherwise I would have to have my build script pull SchemaSpy plus possibly the driver JARs manually from somewhere.

**Comment by marcelstoer** [comment]
Btw, I tried to figure out what SchemaSpy version your plugin uses but I failed.

**Comment by marcelstoer** [comment]
> I tried to figure out what SchemaSpy version your plugin uses

Oh, now I see...you in-sourced their code 😓 Was looking in the wrong places.
Note to self: https://github.com/GeoDienstenCentrum/schemaspy-maven-plugin/tree/master/src/main/java/net/sourceforge/schemaspy

**Comment by mprins** [comment]
> Oh, now I see...you in-sourced their code

yes, because that was the way it was done before I forked this project from https://github.com/wakaleo/maven-schemaspy-plugin .
there is no code from https://github.com/schemaspy/schemaspy here but both share code from the original project at http://schemaspy.sourceforge.net/

**Pull request merged**
